#!/bin/bash

# Count the number of directories and sub-directories in the current directory, including hidden directories
num_dirs=$(find . -mindepth 1 -type d | wc -l)
echo "Number of directories and sub-directories: $num_dirs"
